copyright: Copyright &copy; 2025 OS4D Ltd
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/os4d/jmespath-filters
site_author: Giovanni Bronzini
site_description: ""
site_dir: ./~build/docs
site_name: jmespath-filters
site_url: https://os4d.github.io/os4d/jmespath-filters/
strict: false

theme:
  name: "material"
  color_mode: auto
  custom_dir: docs/_theme/overrides
  favicon: img/favicon.ico
  logo: img/logo.png
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - django
  user_color_mode_toggle: true
  features:
#    - content.action.edit
#    - content.code.annotate
    - content.code.copy
#    - content.tooltips
#    - header.autohide
#    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

watch:
  - docs/
